#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
prg/models/model_gss_K2_q2_s2_custom.py
=======================================
GSS model: K=2 states, q=2 (hidden), s=2 (observed).

Generated by FofGss GUI.
"""

from __future__ import annotations

import numpy as np

from prg.models.base_gss_model import BaseGSSModel

__all__ = ["ModelGssK2Q2S2Custom"]


class ModelGssK2Q2S2Custom(BaseGSSModel):
    """GSS model exported from the GUI (K=2, q=2, s=2)."""

    K: int = 2
    q: int = 2
    s: int = 2

    # --- Markov chain ---
    P: np.ndarray = np.array([[0.95, 0.05],
          [0.05, 0.95]])

    # --- Dynamics: F(k) = [[A_k, B_k], [C_k, D_k]] ---
    A_list: list[np.ndarray] = [np.array([[0.75, 0.05],
          [0, 0.7]]),
     np.array([[0.5, 0.05],
          [0, 0.45]])]
    B_list: list[np.ndarray] = [np.array([[0.0275906, 0.0159614],
          [0.0139175, -0.00198833]]),
     np.array([[0.0202226, 0.0131395],
          [0.00929655, 0.0144188]])]
    C_list: list[np.ndarray] = [np.array([[0.08, 0.06],
          [0.04, 0.1]]),
     np.array([[0.08, 0.06],
          [0.05, 0.1]])]
    D_list: list[np.ndarray] = [np.array([[0.55, 0.03],
          [0.03, 0.5]]),
     np.array([[0.42, 0.04],
          [0.04, 0.4]])]

    # --- Noise covariances: Sigma_W(k) = [[Sigma_U, Delta], [Delta^T, Sigma_V]] ---
    Sigma_U_list: list[np.ndarray] = [np.array([[0.3, 0.05],
          [0.05, 0.25]]),
     np.array([[0.6, -0.08],
          [-0.08, 0.5]])]
    Delta_list:   list[np.ndarray] = [np.array([[0.04, 0.03],
          [0.03, 0.05]]),
     np.array([[0.05, 0.04],
          [0.03, 0.06]])]
    Sigma_V_list: list[np.ndarray] = [np.array([[0.2, 0.04],
          [0.04, 0.15]]),
     np.array([[0.4, 0.06],
          [0.06, 0.35]])]

    # --- Initial conditions ---
    pi0: np.ndarray | None = None   # None → stationary distribution

    mu_z0_list: list[np.ndarray] = [np.array([[0],
          [0],
          [0],
          [0]]),
     np.array([[0],
          [0],
          [0],
          [0]])]
    Sigma_z0_list: list[np.ndarray] = [np.array([[1, 0, 0, 0],
          [0, 1, 0, 0],
          [0, 0, 1, 0],
          [0, 0, 0, 1]]),
     np.array([[1, 0, 0, 0],
          [0, 1, 0, 0],
          [0, 0, 1, 0],
          [0, 0, 0, 1]])]
    b_list: list[np.ndarray] = [np.array([[3],
          [3],
          [0],
          [0]]),
     np.array([[-3],
          [-3],
          [0],
          [0]])]

    # ------------------------------------------------------------------

    def get_params(self) -> dict:
        return {
            "K": self.K, "q": self.q, "s": self.s, "P": self.P,
            "A_list": self.A_list, "B_list": self.B_list,
            "C_list": self.C_list, "D_list": self.D_list,
            "Sigma_U_list": self.Sigma_U_list,
            "Delta_list": self.Delta_list,
            "Sigma_V_list": self.Sigma_V_list,
            "pi0": self.pi0,
            "mu_z0_list": self.mu_z0_list,
            "Sigma_z0_list": self.Sigma_z0_list,
            "b_list": self.b_list,
        }
