#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
prg/models/model_gss_K2_q1_s1_custom.py
=======================================
GSS model: K=2 states, q=1 (hidden), s=1 (observed).

Generated by FofGss GUI.
"""

from __future__ import annotations

import numpy as np

from prg.models.base_gss_model import BaseGSSModel

__all__ = ["ModelGssK2Q1S1Custom"]


class ModelGssK2Q1S1Custom(BaseGSSModel):
    """GSS model exported from the GUI (K=2, q=1, s=1)."""

    K: int = 2
    q: int = 1
    s: int = 1

    # --- Markov chain ---
    P: np.ndarray = np.array([[0.97, 0.03],
          [0.02, 0.98]])

    # --- Dynamics: F(k) = [[A_k, B_k], [C_k, D_k]] ---
    A_list: list[np.ndarray] = [np.array([[0.8]]),
     np.array([[0.5]])]
    B_list: list[np.ndarray] = [np.array([[0.0815534]]),
     np.array([[0.0538691]])]
    C_list: list[np.ndarray] = [np.array([[0.2]]),
     np.array([[0.1]])]
    D_list: list[np.ndarray] = [np.array([[0.7]]),
     np.array([[0.6]])]

    # --- Noise covariances: Sigma_W(k) = [[Sigma_U, Delta], [Delta^T, Sigma_V]] ---
    Sigma_U_list: list[np.ndarray] = [np.array([[0.1]]),
     np.array([[0.2]])]
    Delta_list:   list[np.ndarray] = [np.array([[0.05]]),
     np.array([[0.02]])]
    Sigma_V_list: list[np.ndarray] = [np.array([[0.1]]),
     np.array([[0.15]])]

    # --- Initial conditions ---
    pi0: np.ndarray | None = None   # None → stationary distribution

    mu_z0_list: list[np.ndarray] = [np.array([[0],
          [0]]),
     np.array([[0],
          [0]])]
    Sigma_z0_list: list[np.ndarray] = [np.array([[1, 0],
          [0, 1]]),
     np.array([[1, 0],
          [0, 1]])]
    b_list: list[np.ndarray] = [np.array([[1],
          [2]]),
     np.array([[-2],
          [-1]])]

    # ------------------------------------------------------------------

    def get_params(self) -> dict:
        return {
            "K": self.K, "q": self.q, "s": self.s, "P": self.P,
            "A_list": self.A_list, "B_list": self.B_list,
            "C_list": self.C_list, "D_list": self.D_list,
            "Sigma_U_list": self.Sigma_U_list,
            "Delta_list": self.Delta_list,
            "Sigma_V_list": self.Sigma_V_list,
            "pi0": self.pi0,
            "mu_z0_list": self.mu_z0_list,
            "Sigma_z0_list": self.Sigma_z0_list,
            "b_list": self.b_list,
        }
