#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
prg/models/model_gss_K2_q1_s1.py
================================
GSS model: K=2 states, q=1 (hidden), s=1 (observed).

Generated by exactIMM GUI.
"""

from __future__ import annotations

import numpy as np

from prg.models.base_gss_model import BaseGSSModel

__all__ = ["ModelGssK2Q1S1"]


class ModelGssK2Q1S1(BaseGSSModel):
    """GSS model exported from the GUI (K=2, q=1, s=1)."""

    K: int = 2
    q: int = 1
    s: int = 1

    # --- Markov chain ---
    P: np.ndarray = np.array([[0.97, 0.03],
          [0.02, 0.98]])

    # --- Dynamics: F(k) = [[A_k, B_k], [C_k, D_k]] ---
    # A_k, B_k are not stored: they are derived from (C, D, Δ, Σ_V) in
    # get_params() via the AB constraint (A = Δ Σ_V⁻¹ C, B = Δ Σ_V⁻¹ D),
    # so the model satisfies AB — Markovianity of (R, Y) — by construction.
    C_list: list[np.ndarray] = [np.array([[0.2]]),
     np.array([[0.1]])]
    D_list: list[np.ndarray] = [np.array([[0.7]]),
     np.array([[0.6]])]

    # --- Noise covariances: Sigma_W(k) = [[Sigma_U, Delta], [Delta^T, Sigma_V]] ---
    Sigma_U_list: list[np.ndarray] = [np.array([[0.1]]),
     np.array([[0.2]])]
    Delta_list:   list[np.ndarray] = [np.array([[0.05]]),
     np.array([[0.02]])]
    Sigma_V_list: list[np.ndarray] = [np.array([[0.1]]),
     np.array([[0.15]])]

    # --- Initial conditions ---
    pi0: np.ndarray | None = None   # None → stationary distribution

    mu_z0_list: list[np.ndarray] = [np.array([[0],
          [0]]),
     np.array([[0],
          [0]])]
    Sigma_z0_list: list[np.ndarray] = [np.array([[1, 0],
          [0, 1]]),
     np.array([[1, 0],
          [0, 1]])]
    # Drift bias b(k) = 0: the reference NGH-MSM is zero-mean (paper convention).
    b_list: list[np.ndarray] = [np.zeros((2, 1)), np.zeros((2, 1))]

    # ------------------------------------------------------------------

    def get_params(self) -> dict:
        A_list, B_list = self._ab_constraint(
            self.C_list, self.D_list, self.Delta_list, self.Sigma_V_list
        )
        return {
            "K": self.K, "q": self.q, "s": self.s, "P": self.P,
            "A_list": A_list, "B_list": B_list,
            "C_list": self.C_list, "D_list": self.D_list,
            "Sigma_U_list": self.Sigma_U_list,
            "Delta_list": self.Delta_list,
            "Sigma_V_list": self.Sigma_V_list,
            "pi0": self.pi0,
            "mu_z0_list": self.mu_z0_list,
            "Sigma_z0_list": self.Sigma_z0_list,
            "b_list": self.b_list,
        }
